# Generated by Django 4.2.5 on 2024-04-03 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="director",
            name="user",
        ),
        migrations.RemoveField(
            model_name="planner",
            name="user",
        ),
        migrations.DeleteModel(
            name="Accountant",
        ),
        migrations.DeleteModel(
            name="Director",
        ),
        migrations.DeleteModel(
            name="Planner",
        ),
    ]
