# Generated by Django 4.2.5 on 2024-04-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="graduation_status",
            field=models.CharField(
                choices=[("EX", "Expected"), ("PP", "Postponed")],
                default="EX",
                max_length=2,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seat",
            unique_together={("row", "seat_number")},
        ),
    ]
