# Generated by Django 4.2.5 on 2024-04-19 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_studentprofile_graduation_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="type",
            field=models.CharField(
                choices=[("PRT", "Parent"), ("VIP", "VIP")], default="PRT", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="seatassignment",
            name="student",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.studentprofile",
            ),
        ),
    ]
