# Generated by Django 4.2.5 on 2024-04-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_guest_type_alter_seatassignment_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="tatus",
            field=models.CharField(
                choices=[("EX", "Expected"), ("PP", "Postponed")],
                default="EX",
                max_length=2,
            ),
        ),
    ]
