# Generated by Django 4.2.5 on 2024-05-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_guest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="student",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.studentprofile",
            ),
        ),
    ]
