# Generated by Django 4.2.5 on 2024-04-19 06:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_guest_tatus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guest",
            old_name="tatus",
            new_name="status",
        ),
    ]
