# Generated by Django 4.2.5 on 2024-05-07 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_seatassignment_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seatassignment",
            old_name="student",
            new_name="user",
        ),
    ]
