# Generated by Django 4.2.5 on 2024-05-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_timetable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timetable",
            options={"ordering": ["-start_time"]},
        ),
        migrations.AddField(
            model_name="seatassignment",
            name="link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
